### ISSUE TITLE
passwd file security risk

### ISSUE THREAD

**Issue by Kalivos** [cslug/cslug-site#2]
Passwords should be stored in a database (and off github). It's great that the password is hashed, but it needs to be salted in order to prevent rainbow table lookups. Ideally, you want to use a different salt for every user.

**Comment by glacials** [comment]
The hash was removed from the repository and changed (33305e6c46c5d739b280bea1caad648faa312223), moved to an .htaccess-protected directory and accidentally re-added to the repository (ca4ae1155425f6ea2c689efbef8e4f0023144969), then removed and changed again (c8d15a61d0522d5a6b54390e81e92300b902f72c), but I'm leaving the issue open until it's properly salted (and changed... again).

**Comment by glacials** [comment]
Fixed by fb56212ea4f5814651543cfb3292aef8a970caba.
